export const GET_BUGS = 'get bugs'
export const GET_COMMENTS = 'get comments'
export const ADD_BUG = 'add new bug'

export const REQUEST_GETS = 'request get bugs information'
export const REQUEST_COMMENTSGETS = 'request get comments information'
export const REQUEST_POSTS = 'request post bug information'

export const RECEIVE_BugStatus = 'get bug status'
export const RECEIVE_BugOwner = 'get bug owner'
export const RECEIVE_POSTS = 'receive posts'
export const RECEIVE_PARTBUGS = 'receive part posts'
export const RECEIVE_POSTEDBUG = 'receive posted bug'
export const RECEIVE_BUGDETAIL = 'receive single bug detail'
export const RECEIVE_BUGCOMMENTS = 'receive comments related with one single bug'
export const SELECT_PAGER = 'select pager index'
